<a href="https://colab.research.google.com/github/anishnarkar/DS5500-Project2/blob/master/XceptionNet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os
from urllib.request import urlopen,urlretrieve
from PIL import Image
from tqdm import tqdm_notebook
%matplotlib inline
from sklearn.utils import shuffle
import cv2
#from resnets_utils import *

from keras.models import load_model
from sklearn.datasets import load_files   
from keras.utils import np_utils
from glob import glob
from keras import applications
from keras.preprocessing.image import ImageDataGenerator 
from keras import optimizers
from keras.models import Sequential,Model,load_model
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D,GlobalAveragePooling2D
from keras.callbacks import TensorBoard,ReduceLROnPlateau,ModelCheckpoint

In [0]:
import time
import tensorflow as tf
from sklearn import metrics
import pickle as pi
from collections import Counter
from keras.utils import to_categorical

In [0]:
# d=[1,1]
# while(1):
#   d.append(d)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-c72479f8e2c8>", line 3, in <module>
    d.append(d)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
   

KeyboardInterrupt: ignored

In [0]:
file = open('/content/drive/My Drive/DS5500_Project_2/processed_images/512 by class/array_0.npy', 'rb')
array_0 = np.load(file)
file.close()


In [0]:
sample_size=500
index = np.random.choice(array_0.shape[0], sample_size, replace=False) 

In [0]:
array_0=array_0[index]
np.shape(array_0)

(500, 512, 512, 3)

In [0]:
file = open('/content/drive/My Drive/DS5500_Project_2/processed_images/512 by class/array_1.npy', 'rb')
array_1 = np.load(file)
file.close()
index = np.random.choice(array_1.shape[0], sample_size, replace=False) 
array_1=array_1[index]
np.shape(array_1)

(500, 512, 512, 3)

In [0]:
file = open('/content/drive/My Drive/DS5500_Project_2/processed_images/512 by class/array_2.npy', 'rb')
array_2 = np.load(file)
file.close()
index = np.random.choice(array_2.shape[0], sample_size, replace=False) 
array_2=array_2[index]
np.shape(array_2)

(500, 512, 512, 3)

In [0]:
file = open('/content/drive/My Drive/DS5500_Project_2/processed_images/512 by class/array_3.npy', 'rb')
array_3 = np.load(file)
file.close()
index = np.random.choice(array_3.shape[0], sample_size, replace=False) 
array_3=array_3[index]
np.shape(array_3)

(500, 512, 512, 3)

In [0]:
file = open('/content/drive/My Drive/DS5500_Project_2/processed_images/512 by class/array_4.npy', 'rb')
array_4 = np.load(file)
file.close()
index = np.random.choice(array_4.shape[0], sample_size, replace=False) 
array_4=array_4[index]
np.shape(array_4)

(500, 512, 512, 3)

In [0]:
array_0_label=np.array([0]*sample_size)
array_1_label=np.array([1]*sample_size)
array_2_label=np.array([2]*sample_size)
array_3_label=np.array([3]*sample_size)
array_4_label=np.array([4]*sample_size)

In [0]:
train_set=np.concatenate([array_0,array_1,array_2,array_3,array_4])
label_set=np.concatenate([array_0_label,array_1_label,array_2_label,array_3_label,array_4_label])

In [0]:
#removing variables to vacate memory
del array_0
del array_1
del array_2
del array_3
del array_4
del array_0_label
del array_1_label
del array_2_label
del array_3_label
del array_4_label

In [0]:
np.shape(label_set)

(2500,)

In [0]:
from sklearn.utils import shuffle
train_set, label_set = shuffle(train_set, label_set, random_state=500)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(train_set, label_set, test_size=0.2, random_state=500)

In [0]:
np.shape(y_test)

(500,)

In [0]:
train_labels = to_categorical(y_train, 5)
test_labels= to_categorical(y_test,5)

In [0]:
from keras.applications.xception import Xception

In [0]:
img_sz = 512
img_height,img_width = img_sz, img_sz
num_classes = 5
#If imagenet weights are being loaded, 
#input must have a static square shape (one of (128, 128), (160, 160), (192, 192), or (224, 224))
base_model = Xception(weights= None, include_top=False, input_shape= (img_height,img_width,3))

In [0]:
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
predictions = Dense(num_classes, activation= 'sigmoid')(x)
model = Model(inputs = base_model.input, outputs = predictions)

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [0]:
from keras.optimizers import SGD, Adam, Adadelta
# sgd = SGD(lr=lrate, momentum=0.9, decay=decay, nesterov=False)
adam = Adadelta(lr=0.01)
model.compile(optimizer= adam, loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
print('start time:'+str(time.time()))
model.fit(X_train, train_labels  , epochs = 5, batch_size = 32)
print('end time:'+str(time.time()))

start time:1574710855.272542
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/5


ResourceExhaustedError: ignored

In [0]:
y_train

array([2, 2, 4, ..., 3, 2, 0])

In [0]:
label_set

array([0, 0, 0, ..., 4, 4, 4])

In [0]:
test1=np.array([1,2,3,4])
test2=np.array([5,6,7,8])
test3=np.array([11,12])
np.concatenate([test1,test2,test3])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 12])